//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public int id { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> adres_id { get; set; }
        public Nullable<int> kontakt_id { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Kontakt Kontakt { get; set; }
    }
}
