//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jadlospis
    {
        public int id { get; set; }
        public System.DateTime od { get; set; }
        public System.DateTime @do { get; set; }
        public Nullable<int> poniedzialek { get; set; }
        public Nullable<int> wtorek { get; set; }
        public Nullable<int> sroda { get; set; }
        public Nullable<int> czwartek { get; set; }
        public Nullable<int> piatek { get; set; }
    
        public virtual Posilek Posilek { get; set; }
        public virtual Posilek Posilek1 { get; set; }
        public virtual Posilek Posilek2 { get; set; }
        public virtual Posilek Posilek3 { get; set; }
        public virtual Posilek Posilek4 { get; set; }
    }
}
