//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nieobecnosc
    {
        public int id { get; set; }
        public System.DateTime od { get; set; }
        public System.DateTime @do { get; set; }
        public int dziecko_id { get; set; }
    
        public virtual Dziecko Dziecko { get; set; }
    }
}
