//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oplata()
        {
            this.Transakcja = new HashSet<Transakcja>();
        }
    
        public int id { get; set; }
        public int miesiac_id { get; set; }
        public int rok_id { get; set; }
        public float stawka_za_dzien { get; set; }
        public int dni_w_miesiacu { get; set; }
        public float cena => stawka_za_dzien * dni_w_miesiacu;

        public virtual Miesiac Miesiac { get; set; }
        public virtual Rok Rok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcja> Transakcja { get; set; }
    }
}
