//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string stanowisko { get; set; }
        public int adres_id { get; set; }
        public Nullable<int> kontakt_id { get; set; }
        public string konto_id { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
